<?php

use Illuminate\Database\Seeder;

class RegionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('regions')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        DB::table('regions')->insert([
        	['api' =>'megaindex', 'name' =>'Планета Земля', 'yandex_index' =>'-1', 'google_index' =>'-1'],
            ['api' =>'megaindex', 'name' =>'Без учета региона', 'yandex_index' =>'0', 'google_index' =>'0'],
            ['api' =>'megaindex', 'name' =>'Европа', 'yandex_index' =>'111', 'google_index' =>'111'],
            ['api' =>'megaindex', 'name' =>'СНГ', 'yandex_index' =>'166', 'google_index' =>'166'],
            ['api' =>'megaindex', 'name' =>'Универсальное', 'yandex_index' =>'318', 'google_index' =>'318'],
            ['api' =>'megaindex', 'name' =>'Азия', 'yandex_index' =>'183', 'google_index' =>'183'],
            ['api' =>'megaindex', 'name' =>'Россия', 'yandex_index' =>'225', 'google_index' =>'225'],
            ['api' =>'megaindex', 'name' =>'Северо-Западный федеральный округ', 'yandex_index' =>'17', 'google_index' =>'17'],
            ['api' =>'megaindex', 'name' =>'Калининградская область', 'yandex_index' =>'10857', 'google_index' =>'10857'],
            ['api' =>'megaindex', 'name' =>'Калининград', 'yandex_index' =>'22', 'google_index' =>'22'],
            ['api' =>'megaindex', 'name' =>'Мурманская область', 'yandex_index' =>'10897', 'google_index' =>'10897'],
            ['api' =>'megaindex', 'name' =>'Мурманск', 'yandex_index' =>'23', 'google_index' =>'23'],
            ['api' =>'megaindex', 'name' =>'Республика Карелия', 'yandex_index' =>'10933', 'google_index' =>'10933'],
            ['api' =>'megaindex', 'name' =>'Петрозаводск', 'yandex_index' =>'18', 'google_index' =>'18'],
            ['api' =>'megaindex', 'name' =>'Санкт-Петербург и Ленинградская область', 'yandex_index' =>'10174', 'google_index' =>'10174'],
            ['api' =>'megaindex', 'name' =>'Санкт-Петербург', 'yandex_index' =>'2', 'google_index' =>'2'],
            ['api' =>'megaindex', 'name' =>'Псковская область', 'yandex_index' =>'10926', 'google_index' =>'10926'],
            ['api' =>'megaindex', 'name' =>'Псков', 'yandex_index' =>'25', 'google_index' =>'25'],
            ['api' =>'megaindex', 'name' =>'Великие Луки', 'yandex_index' =>'10928', 'google_index' =>'10928'],
            ['api' =>'megaindex', 'name' =>'Новгородская область', 'yandex_index' =>'10904', 'google_index' =>'10904'],
            ['api' =>'megaindex', 'name' =>'Великий Новгород', 'yandex_index' =>'24', 'google_index' =>'24'],
            ['api' =>'megaindex', 'name' =>'Центральный федеральный округ', 'yandex_index' =>'3', 'google_index' =>'3'],
            ['api' =>'megaindex', 'name' =>'Тверская область', 'yandex_index' =>'10819', 'google_index' =>'10819'],
            ['api' =>'megaindex', 'name' =>'Тверь', 'yandex_index' =>'14', 'google_index' =>'14'],
            ['api' =>'megaindex', 'name' =>'Смоленская область', 'yandex_index' =>'10795', 'google_index' =>'10795'],
            ['api' =>'megaindex', 'name' =>'Смоленск', 'yandex_index' =>'12', 'google_index' =>'12'],
            ['api' =>'megaindex', 'name' =>'Брянская область', 'yandex_index' =>'10650', 'google_index' =>'10650'],
            ['api' =>'megaindex', 'name' =>'Брянск', 'yandex_index' =>'191', 'google_index' =>'191'],
            ['api' =>'megaindex', 'name' =>'Калужская область', 'yandex_index' =>'10693'   , 'google_index' =>'10693'   ],
            ['api' =>'megaindex', 'name' =>'Калуга', 'yandex_index' =>'6', 'google_index' =>'6'],
            ['api' =>'megaindex', 'name' =>'Обнинск', 'yandex_index' =>'967', 'google_index' =>'967'],
            ['api' =>'megaindex', 'name' =>'Курская область', 'yandex_index' =>'10705', 'google_index' =>'10705'],
            ['api' =>'megaindex', 'name' =>'Курск', 'yandex_index' =>'8', 'google_index' =>'8'],
            ['api' =>'megaindex', 'name' =>'Орловская область', 'yandex_index' =>'10772', 'google_index' =>'10772'],
            ['api' =>'megaindex', 'name' =>'Орёл', 'yandex_index' =>'10', 'google_index' =>'10'],
            ['api' =>'megaindex', 'name' =>'Тульская область', 'yandex_index' =>'10832', 'google_index' =>'10832'],
            ['api' =>'megaindex', 'name' =>'Тула', 'yandex_index' =>'15', 'google_index' =>'15'],
            ['api' =>'megaindex', 'name' =>'Москва и Московская область', 'yandex_index' =>'1', 'google_index' =>'1'],
            ['api' =>'megaindex', 'name' =>'Москва', 'yandex_index' =>'213', 'google_index' =>'213'],
            ['api' =>'megaindex', 'name' =>'Долгопрудный', 'yandex_index' =>'214', 'google_index' =>'214'],
            ['api' =>'megaindex', 'name' =>'Дубна', 'yandex_index' =>'215', 'google_index' =>'215'],
            ['api' =>'megaindex', 'name' =>'Зеленоград', 'yandex_index' =>'216', 'google_index' =>'216'],
            ['api' =>'megaindex', 'name' =>'Пущино', 'yandex_index' =>'217', 'google_index' =>'217'],
            ['api' =>'megaindex', 'name' =>'Белгородская область', 'yandex_index' =>'10645', 'google_index' =>'10645'],
            ['api' =>'megaindex', 'name' =>'Белгород', 'yandex_index' =>'4', 'google_index' =>'4'],
            ['api' =>'megaindex', 'name' =>'Липецкая область', 'yandex_index' =>'10712', 'google_index' =>'10712'],
            ['api' =>'megaindex', 'name' =>'Липецк', 'yandex_index' =>'9', 'google_index' =>'9'],
            ['api' =>'megaindex', 'name' =>'Ярославская область', 'yandex_index' =>'10841', 'google_index' =>'10841'],
            ['api' =>'megaindex', 'name' =>'Ярославль', 'yandex_index' =>'16', 'google_index' =>'16'],
            ['api' =>'megaindex', 'name' =>'Владимирская область', 'yandex_index' =>'10658', 'google_index' =>'10658'],
            ['api' =>'megaindex', 'name' =>'Владимир', 'yandex_index' =>'192', 'google_index' =>'192'],
            ['api' =>'megaindex', 'name' =>'Александров', 'yandex_index' =>'10656', 'google_index' =>'10656'],
            ['api' =>'megaindex', 'name' =>'Гусь-Хрустальный', 'yandex_index' =>'10661', 'google_index' =>'10661'],
            ['api' =>'megaindex', 'name' =>'Муром', 'yandex_index' =>'10668', 'google_index' =>'10668'],
            ['api' =>'megaindex', 'name' =>'Ивановская область', 'yandex_index' =>'10687', 'google_index' =>'10687'],
            ['api' =>'megaindex', 'name' =>'Иваново', 'yandex_index' =>'5', 'google_index' =>'5'],
            ['api' =>'megaindex', 'name' =>'Рязанская область', 'yandex_index' =>'10776', 'google_index' =>'10776'],
            ['api' =>'megaindex', 'name' =>'Рязань', 'yandex_index' =>'11', 'google_index' =>'11'],
            ['api' =>'megaindex', 'name' =>'Тамбовская область', 'yandex_index' =>'10802', 'google_index' =>'10802'],
            ['api' =>'megaindex', 'name' =>'Тамбов', 'yandex_index' =>'13', 'google_index' =>'13'],
            ['api' =>'megaindex', 'name' =>'Воронежская область', 'yandex_index' =>'10672', 'google_index' =>'10672'],
            ['api' =>'megaindex', 'name' =>'Воронеж', 'yandex_index' =>'193', 'google_index' =>'193'],
            ['api' =>'megaindex', 'name' =>'Южный федеральный округ', 'yandex_index' =>'26', 'google_index' =>'26'],
            ['api' =>'megaindex', 'name' =>'Ростовская область', 'yandex_index' =>'11029', 'google_index' =>'11029'],
            ['api' =>'megaindex', 'name' =>'Ростов-на-Дону', 'yandex_index' =>'39', 'google_index' =>'39'],
            ['api' =>'megaindex', 'name' =>'Шахты', 'yandex_index' =>'11053', 'google_index' =>'11053'],
            ['api' =>'megaindex', 'name' =>'Таганрог', 'yandex_index' =>'971', 'google_index' =>'971'],
            ['api' =>'megaindex', 'name' =>'Новочеркасск', 'yandex_index' =>'238', 'google_index' =>'238'],
            ['api' =>'megaindex', 'name' =>'Волгодонск', 'yandex_index' =>'11036', 'google_index' =>'11036'],
            ['api' =>'megaindex', 'name' =>'Краснодарский край', 'yandex_index' =>'10995', 'google_index' =>'10995'],
            ['api' =>'megaindex', 'name' =>'Краснодар', 'yandex_index' =>'35', 'google_index' =>'35'],
            ['api' =>'megaindex', 'name' =>'Анапа', 'yandex_index' =>'1107', 'google_index' =>'1107'],
            ['api' =>'megaindex', 'name' =>'Новороссийск', 'yandex_index' =>'970', 'google_index' =>'970'],
            ['api' =>'megaindex', 'name' =>'Сочи', 'yandex_index' =>'239', 'google_index' =>'239'],
            ['api' =>'megaindex', 'name' =>'Туапсе', 'yandex_index' =>'1058', 'google_index' =>'1058'],
            ['api' =>'megaindex', 'name' =>'Геленджик', 'yandex_index' =>'10990', 'google_index' =>'10990'],
            ['api' =>'megaindex', 'name' =>'Армавир', 'yandex_index' =>'10987', 'google_index' =>'10987'],
            ['api' =>'megaindex', 'name' =>'Ейск', 'yandex_index' =>'10993', 'google_index' =>'10993'],
            ['api' =>'megaindex', 'name' =>'Республика Адыгея', 'yandex_index' =>'11004', 'google_index' =>'11004'],
            ['api' =>'megaindex', 'name' =>'Майкоп', 'yandex_index' =>'1093', 'google_index' =>'1093'],
            ['api' =>'megaindex', 'name' =>'Карачаево-Черкесская республика', 'yandex_index' =>'11020', 'google_index' =>'11020'],
            ['api' =>'megaindex', 'name' =>'Черкесск', 'yandex_index' =>'1104', 'google_index' =>'1104'],
            ['api' =>'megaindex', 'name' =>'Кабардино-Балкарская республика', 'yandex_index' =>'11013', 'google_index' =>'11013'],
            ['api' =>'megaindex', 'name' =>'(Республика Кабардино-Балкария)', 'yandex_index' =>'', 'google_index' =>''],
            ['api' =>'megaindex', 'name' =>'Нальчик', 'yandex_index' =>'30', 'google_index' =>'30'],
            ['api' =>'megaindex', 'name' =>'Северная Осетия', 'yandex_index' =>'11021', 'google_index' =>'11021'],
            ['api' =>'megaindex', 'name' =>'(Республика Северная Осетия-Алания)', 'yandex_index' =>'', 'google_index' =>''],
            ['api' =>'megaindex', 'name' =>'Владикавказ', 'yandex_index' =>'33', 'google_index' =>'33'],
            ['api' =>'megaindex', 'name' =>'Республика Ингушетия', 'yandex_index' =>'11012', 'google_index' =>'11012'],
            ['api' =>'megaindex', 'name' =>'Чеченская республика', 'yandex_index' =>'11024', 'google_index' =>'11024'],
            ['api' =>'megaindex', 'name' =>'(Чечня)', 'yandex_index' =>'', 'google_index' =>''],
            ['api' =>'megaindex', 'name' =>'Грозный', 'yandex_index' =>'1106', 'google_index' =>'1106'],
            ['api' =>'megaindex', 'name' =>'Республика Дагестан', 'yandex_index' =>'11010', 'google_index' =>'11010'],
            ['api' =>'megaindex', 'name' =>'Махачкала', 'yandex_index' =>'28', 'google_index' =>'28'],
            ['api' =>'megaindex', 'name' =>'Ставропольский край', 'yandex_index' =>'11069', 'google_index' =>'11069'],
            ['api' =>'megaindex', 'name' =>'Ставрополь', 'yandex_index' =>'36', 'google_index' =>'36'],
            ['api' =>'megaindex', 'name' =>'Каменск-Шахтинский', 'yandex_index' =>'11043', 'google_index' =>'11043'],
            ['api' =>'megaindex', 'name' =>'Пятигорск', 'yandex_index' =>'11067', 'google_index' =>'11067'],
            ['api' =>'megaindex', 'name' =>'Минеральные Воды', 'yandex_index' =>'11063', 'google_index' =>'11063'],
            ['api' =>'megaindex', 'name' =>'Ессентуки', 'yandex_index' =>'11057', 'google_index' =>'11057'],
            ['api' =>'megaindex', 'name' =>'Кисловодск', 'yandex_index' =>'11062', 'google_index' =>'11062'],
            ['api' =>'megaindex', 'name' =>'Республика Калмыкия', 'yandex_index' =>'11015', 'google_index' =>'11015'],
            ['api' =>'megaindex', 'name' =>'Элиста', 'yandex_index' =>'1094', 'google_index' =>'1094'],
            ['api' =>'megaindex', 'name' =>'Астраханская область', 'yandex_index' =>'10946', 'google_index' =>'10946'],
            ['api' =>'megaindex', 'name' =>'Астрахань', 'yandex_index' =>'37', 'google_index' =>'37'],
            ['api' =>'megaindex', 'name' =>'Волгоградская область', 'yandex_index' =>'10950', 'google_index' =>'10950'],
            ['api' =>'megaindex', 'name' =>'Волгоград', 'yandex_index' =>'38', 'google_index' =>'38'],
            ['api' =>'megaindex', 'name' =>'Приволжский федеральный округ', 'yandex_index' =>'40', 'google_index' =>'40'],
            ['api' =>'megaindex', 'name' =>'(Поволжье)', 'yandex_index' =>'', 'google_index' =>''],
            ['api' =>'megaindex', 'name' =>'Саратовская область', 'yandex_index' =>'11146', 'google_index' =>'11146'],
            ['api' =>'megaindex', 'name' =>'Саратов', 'yandex_index' =>'194', 'google_index' =>'194'],
            ['api' =>'megaindex', 'name' =>'Жигулевск', 'yandex_index' =>'11132', 'google_index' =>'11132'],
            ['api' =>'megaindex', 'name' =>'Балаково', 'yandex_index' =>'11143', 'google_index' =>'11143'],
            ['api' =>'megaindex', 'name' =>'Пензенская область', 'yandex_index' =>'11095', 'google_index' =>'11095'],
            ['api' =>'megaindex', 'name' =>'Пенза', 'yandex_index' =>'49', 'google_index' =>'49'],
            ['api' =>'megaindex', 'name' =>'Республика Мордовия', 'yandex_index' =>'11117', 'google_index' =>'11117'],
            ['api' =>'megaindex', 'name' =>'Саранск', 'yandex_index' =>'42', 'google_index' =>'42'],
            ['api' =>'megaindex', 'name' =>'Ульяновская область', 'yandex_index' =>'11153', 'google_index' =>'11153'],
            ['api' =>'megaindex', 'name' =>'Ульяновск', 'yandex_index' =>'195', 'google_index' =>'195'],
            ['api' =>'megaindex', 'name' =>'Самарская область', 'yandex_index' =>'11131', 'google_index' =>'11131'],
            ['api' =>'megaindex', 'name' =>'Самара', 'yandex_index' =>'51', 'google_index' =>'51'],
            ['api' =>'megaindex', 'name' =>'Тольятти', 'yandex_index' =>'240', 'google_index' =>'240'],
            ['api' =>'megaindex', 'name' =>'Сызрань', 'yandex_index' =>'11139', 'google_index' =>'11139'],
            ['api' =>'megaindex', 'name' =>'Чувашская республика', 'yandex_index' =>'11156', 'google_index' =>'11156'],
            ['api' =>'megaindex', 'name' =>'Чебоксары', 'yandex_index' =>'45', 'google_index' =>'45'],
            ['api' =>'megaindex', 'name' =>'Республика Марий Эл', 'yandex_index' =>'11077', 'google_index' =>'11077'],
            ['api' =>'megaindex', 'name' =>'Йошкар-Ола', 'yandex_index' =>'41', 'google_index' =>'41'],
            ['api' =>'megaindex', 'name' =>'Нижегородская область', 'yandex_index' =>'11079', 'google_index' =>'11079'],
            ['api' =>'megaindex', 'name' =>'Нижний Новгород', 'yandex_index' =>'47', 'google_index' =>'47'],
            ['api' =>'megaindex', 'name' =>'Саров', 'yandex_index' =>'11083', 'google_index' =>'11083'],
            ['api' =>'megaindex', 'name' =>'Кировская область', 'yandex_index' =>'11070', 'google_index' =>'11070'],
            ['api' =>'megaindex', 'name' =>'Киров', 'yandex_index' =>'46', 'google_index' =>'46'],
            ['api' =>'megaindex', 'name' =>'Костромская область', 'yandex_index' =>'10699', 'google_index' =>'10699'],
            ['api' =>'megaindex', 'name' =>'Кострома', 'yandex_index' =>'7', 'google_index' =>'7'],
            ['api' =>'megaindex', 'name' =>'Вологодская область', 'yandex_index' =>'10853', 'google_index' =>'10853'],
            ['api' =>'megaindex', 'name' =>'Вологда', 'yandex_index' =>'21', 'google_index' =>'21'],
            ['api' =>'megaindex', 'name' =>'Архангельская область', 'yandex_index' =>'10842', 'google_index' =>'10842'],
            ['api' =>'megaindex', 'name' =>'Архангельск', 'yandex_index' =>'20', 'google_index' =>'20'],
            ['api' =>'megaindex', 'name' =>'Северодвинск', 'yandex_index' =>'10849', 'google_index' =>'10849'],
            ['api' =>'megaindex', 'name' =>'Ненецкий автономный округ', 'yandex_index' =>'10176', 'google_index' =>'10176'],
            ['api' =>'megaindex', 'name' =>'Республика Коми', 'yandex_index' =>'10939', 'google_index' =>'10939'],
            ['api' =>'megaindex', 'name' =>'Сыктывкар', 'yandex_index' =>'19', 'google_index' =>'19'],
            ['api' =>'megaindex', 'name' =>'Удмуртская республика', 'yandex_index' =>'11148', 'google_index' =>'11148'],
            ['api' =>'megaindex', 'name' =>'Ижевск', 'yandex_index' =>'44', 'google_index' =>'44'],
            ['api' =>'megaindex', 'name' =>'Республика Татарстан', 'yandex_index' =>'11119', 'google_index' =>'11119'],
            ['api' =>'megaindex', 'name' =>'Казань', 'yandex_index' =>'43', 'google_index' =>'43'],
            ['api' =>'megaindex', 'name' =>'Набережные Челны', 'yandex_index' =>'236', 'google_index' =>'236'],
            ['api' =>'megaindex', 'name' =>'Нижнекамск', 'yandex_index' =>'11127', 'google_index' =>'11127'],
            ['api' =>'megaindex', 'name' =>'Пермский край', 'yandex_index' =>'11108', 'google_index' =>'11108'],
            ['api' =>'megaindex', 'name' =>'Пермь', 'yandex_index' =>'50', 'google_index' =>'50'],
            ['api' =>'megaindex', 'name' =>'Республика Башкортостан', 'yandex_index' =>'11111', 'google_index' =>'11111'],
            ['api' =>'megaindex', 'name' =>'Уфа', 'yandex_index' =>'172', 'google_index' =>'172'],
            ['api' =>'megaindex', 'name' =>'Нефтекамск', 'yandex_index' =>'11114', 'google_index' =>'11114'],
            ['api' =>'megaindex', 'name' =>'Салават', 'yandex_index' =>'11115', 'google_index' =>'11115'],
            ['api' =>'megaindex', 'name' =>'Стерлитамак', 'yandex_index' =>'11116', 'google_index' =>'11116'],
            ['api' =>'megaindex', 'name' =>'Оренбургская область', 'yandex_index' =>'11084', 'google_index' =>'11084'],
            ['api' =>'megaindex', 'name' =>'Оренбург', 'yandex_index' =>'48', 'google_index' =>'48'],
            ['api' =>'megaindex', 'name' =>'Дзержинск', 'yandex_index' =>'972', 'google_index' =>'972'],
            ['api' =>'megaindex', 'name' =>'Уральский федеральный округ', 'yandex_index' =>'52', 'google_index' =>'52'],
            ['api' =>'megaindex', 'name' =>'(Урал)', 'yandex_index' =>'', 'google_index' =>''],
            ['api' =>'megaindex', 'name' =>'Челябинская область', 'yandex_index' =>'11225', 'google_index' =>'11225'],
            ['api' =>'megaindex', 'name' =>'Челябинск', 'yandex_index' =>'56', 'google_index' =>'56'],
            ['api' =>'megaindex', 'name' =>'Магнитогорск', 'yandex_index' =>'235', 'google_index' =>'235'],
            ['api' =>'megaindex', 'name' =>'Снежинск', 'yandex_index' =>'11218', 'google_index' =>'11218'],
            ['api' =>'megaindex', 'name' =>'Курганская область', 'yandex_index' =>'11158', 'google_index' =>'11158'],
            ['api' =>'megaindex', 'name' =>'Курган', 'yandex_index' =>'53', 'google_index' =>'53'],
            ['api' =>'megaindex', 'name' =>'Свердловская область', 'yandex_index' =>'11162', 'google_index' =>'11162'],
            ['api' =>'megaindex', 'name' =>'Екатеринбург', 'yandex_index' =>'54', 'google_index' =>'54'],
            ['api' =>'megaindex', 'name' =>'Каменск-Уральский', 'yandex_index' =>'11164', 'google_index' =>'11164'],
            ['api' =>'megaindex', 'name' =>'Нижний Тагил', 'yandex_index' =>'11168', 'google_index' =>'11168'],
            ['api' =>'megaindex', 'name' =>'Новоуральск', 'yandex_index' =>'11170', 'google_index' =>'11170'],
            ['api' =>'megaindex', 'name' =>'Первоуральск', 'yandex_index' =>'11171', 'google_index' =>'11171'],
            ['api' =>'megaindex', 'name' =>'Тюменская область', 'yandex_index' =>'11176', 'google_index' =>'11176'],
            ['api' =>'megaindex', 'name' =>'Тюмень', 'yandex_index' =>'55', 'google_index' =>'55'],
            ['api' =>'megaindex', 'name' =>'Тобольск', 'yandex_index' =>'11175', 'google_index' =>'11175'],
            ['api' =>'megaindex', 'name' =>'Ханты-Мансийский автономный округ', 'yandex_index' =>'11193', 'google_index' =>'11193'],
            ['api' =>'megaindex', 'name' =>'Ханты-Мансийск', 'yandex_index' =>'57', 'google_index' =>'57'],
            ['api' =>'megaindex', 'name' =>'Сургут', 'yandex_index' =>'973', 'google_index' =>'973'],
            ['api' =>'megaindex', 'name' =>'Нижневартовск', 'yandex_index' =>'1091', 'google_index' =>'1091'],
            ['api' =>'megaindex', 'name' =>'Сибирский Федеральный округ', 'yandex_index' =>'59', 'google_index' =>'59'],
            ['api' =>'megaindex', 'name' =>'(Сибирь)', 'yandex_index' =>'', 'google_index' =>''],
            ['api' =>'megaindex', 'name' =>'Омская область', 'yandex_index' =>'11318', 'google_index' =>'11318'],
            ['api' =>'megaindex', 'name' =>'Омск', 'yandex_index' =>'66', 'google_index' =>'66'],
            ['api' =>'megaindex', 'name' =>'Новосибирская область', 'yandex_index' =>'11316', 'google_index' =>'11316'],
            ['api' =>'megaindex', 'name' =>'Новосибирск', 'yandex_index' =>'65', 'google_index' =>'65'],
            ['api' =>'megaindex', 'name' =>'Бердск', 'yandex_index' =>'11314', 'google_index' =>'11314'],
            ['api' =>'megaindex', 'name' =>'Томская область', 'yandex_index' =>'11353', 'google_index' =>'11353'],
            ['api' =>'megaindex', 'name' =>'Томск', 'yandex_index' =>'67', 'google_index' =>'67'],
            ['api' =>'megaindex', 'name' =>'Ямало-Ненецкий автономный округ', 'yandex_index' =>'11232', 'google_index' =>'11232'],
            ['api' =>'megaindex', 'name' =>'Салехард', 'yandex_index' =>'58', 'google_index' =>'58'],
            ['api' =>'megaindex', 'name' =>'Алтайский край', 'yandex_index' =>'11235', 'google_index' =>'11235'],
            ['api' =>'megaindex', 'name' =>'Барнаул', 'yandex_index' =>'197', 'google_index' =>'197'],
            ['api' =>'megaindex', 'name' =>'Бийск', 'yandex_index' =>'975', 'google_index' =>'975'],
            ['api' =>'megaindex', 'name' =>'Рубцовск', 'yandex_index' =>'11251', 'google_index' =>'11251'],
            ['api' =>'megaindex', 'name' =>'Республика Алтай', 'yandex_index' =>'10231', 'google_index' =>'10231'],
            ['api' =>'megaindex', 'name' =>'Горно-Алтайск', 'yandex_index' =>'11319', 'google_index' =>'11319'],
            ['api' =>'megaindex', 'name' =>'Кемеровская область', 'yandex_index' =>'11282', 'google_index' =>'11282'],
            ['api' =>'megaindex', 'name' =>'Кемерово', 'yandex_index' =>'64', 'google_index' =>'64'],
            ['api' =>'megaindex', 'name' =>'Междуреченск', 'yandex_index' =>'11287', 'google_index' =>'11287'],
            ['api' =>'megaindex', 'name' =>'Новокузнецк', 'yandex_index' =>'237', 'google_index' =>'237'],
            ['api' =>'megaindex', 'name' =>'Прокопьевск', 'yandex_index' =>'11291', 'google_index' =>'11291'],
            ['api' =>'megaindex', 'name' =>'Республика Хакасия', 'yandex_index' =>'11340', 'google_index' =>'11340'],
            ['api' =>'megaindex', 'name' =>'Абакан', 'yandex_index' =>'1095', 'google_index' =>'1095'],
            ['api' =>'megaindex', 'name' =>'Республика Тыва', 'yandex_index' =>'10233', 'google_index' =>'10233'],
            ['api' =>'megaindex', 'name' =>'Кызыл', 'yandex_index' =>'11333', 'google_index' =>'11333'],
            ['api' =>'megaindex', 'name' =>'Красноярский край', 'yandex_index' =>'11309', 'google_index' =>'11309'],
            ['api' =>'megaindex', 'name' =>'Красноярск', 'yandex_index' =>'62', 'google_index' =>'62'],
            ['api' =>'megaindex', 'name' =>'Ачинск', 'yandex_index' =>'11302', 'google_index' =>'11302'],
            ['api' =>'megaindex', 'name' =>'Норильск', 'yandex_index' =>'11311', 'google_index' =>'11311'],
            ['api' =>'megaindex', 'name' =>'Железногорск', 'yandex_index' =>'20086', 'google_index' =>'20086'],
            ['api' =>'megaindex', 'name' =>'Иркутская область', 'yandex_index' =>'11266', 'google_index' =>'11266'],
            ['api' =>'megaindex', 'name' =>'Иркутск', 'yandex_index' =>'63', 'google_index' =>'63'],
            ['api' =>'megaindex', 'name' =>'Братск', 'yandex_index' =>'976', 'google_index' =>'976'],
            ['api' =>'megaindex', 'name' =>'Республика Бурятия', 'yandex_index' =>'11330', 'google_index' =>'11330'],
            ['api' =>'megaindex', 'name' =>'Улан-Удэ', 'yandex_index' =>'198', 'google_index' =>'198'],
            ['api' =>'megaindex', 'name' =>'Забайкальский край', 'yandex_index' =>'21949', 'google_index' =>'21949'],
            ['api' =>'megaindex', 'name' =>'Чита', 'yandex_index' =>'68', 'google_index' =>'68'],
            ['api' =>'megaindex', 'name' =>'Дальневосточный федеральный округ', 'yandex_index' =>'73', 'google_index' =>'73'],
            ['api' =>'megaindex', 'name' =>'(Дальний Восток)', 'yandex_index' =>'', 'google_index' =>''],
            ['api' =>'megaindex', 'name' =>'Республика Саха (Якутия)', 'yandex_index' =>'11443', 'google_index' =>'11443'],
            ['api' =>'megaindex', 'name' =>'Якутск', 'yandex_index' =>'74', 'google_index' =>'74'],
            ['api' =>'megaindex', 'name' =>'Амурская область', 'yandex_index' =>'11375', 'google_index' =>'11375'],
            ['api' =>'megaindex', 'name' =>'Благовещенск', 'yandex_index' =>'77', 'google_index' =>'77'],
            ['api' =>'megaindex', 'name' =>'Еврейская автономная область', 'yandex_index' =>'10243', 'google_index' =>'10243'],
            ['api' =>'megaindex', 'name' =>'Биробиджан', 'yandex_index' =>'11393', 'google_index' =>'11393'],
            ['api' =>'megaindex', 'name' =>'Приморский край', 'yandex_index' =>'11409', 'google_index' =>'11409'],
            ['api' =>'megaindex', 'name' =>'Владивосток', 'yandex_index' =>'75', 'google_index' =>'75'],
            ['api' =>'megaindex', 'name' =>'Находка', 'yandex_index' =>'974', 'google_index' =>'974'],
            ['api' =>'megaindex', 'name' =>'Уссурийск', 'yandex_index' =>'11426', 'google_index' =>'11426'],
            ['api' =>'megaindex', 'name' =>'Чукотский автономный округ', 'yandex_index' =>'10251', 'google_index' =>'10251'],
            ['api' =>'megaindex', 'name' =>'Анадырь', 'yandex_index' =>'11458', 'google_index' =>'11458'],
            ['api' =>'megaindex', 'name' =>'Камчатский край', 'yandex_index' =>'11398', 'google_index' =>'11398'],
            ['api' =>'megaindex', 'name' =>'Петропавловск-Камчатский', 'yandex_index' =>'78', 'google_index' =>'78'],
            ['api' =>'megaindex', 'name' =>'Магаданская область', 'yandex_index' =>'11403', 'google_index' =>'11403'],
            ['api' =>'megaindex', 'name' =>'Магадан', 'yandex_index' =>'79', 'google_index' =>'79'],
            ['api' =>'megaindex', 'name' =>'Сахалинская область', 'yandex_index' =>'11450', 'google_index' =>'11450'],
            ['api' =>'megaindex', 'name' =>'Южно-Сахалинск', 'yandex_index' =>'80', 'google_index' =>'80'],
            ['api' =>'megaindex', 'name' =>'Хабаровский край', 'yandex_index' =>'11457', 'google_index' =>'11457'],
            ['api' =>'megaindex', 'name' =>'Хабаровск', 'yandex_index' =>'76', 'google_index' =>'76'],
            ['api' =>'megaindex', 'name' =>'Комсомольск-на-Амуре', 'yandex_index' =>'11453', 'google_index' =>'11453'],
            ['api' =>'megaindex', 'name' =>'Украина', 'yandex_index' =>'187', 'google_index' =>'187'],
            ['api' =>'megaindex', 'name' =>'Беларусь', 'yandex_index' =>'149', 'google_index' =>'149'],
            ['api' =>'megaindex', 'name' =>'Казахстан', 'yandex_index' =>'159', 'google_index' =>'159']
        ]);
    }
}
